### PR TITLE
corrects references on generated scaladoc

### PR DESCRIPTION
**Pull request by datalek**
# Pull Request Checklist
- [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
- [ ] Have you read through the [contributor guidelines](https://github.com/mohiva/silhouette-akka-http/blob/master/CONTRIBUTING.md)?
- [x] Have you [squashed your commits](https://www.playframework.com/documentation/2.5.x/WorkingWithGit#Squashing-commits)?
- [x] Have you added copyright headers to new files?
- [x] Have you suggest documentation edits?
- [x] Have you added tests for any changed functionality?
## Purpose

Correct some problem during doc generation, caused by bad references

### CODE REVIEW

**Comment by akkie** [comment]
I think it's better if we capitalize the commit messages. [This](http://chris.beams.io/posts/git-commit/) is a good reference on how to write good commit messages.

Anyway, the commit doesn't really fix the main problem. It seems that the doc task cannot create a reference to to the silhouette or the akka-http classes. Normally this should be fixed by adding the resources to the [BuildSettings](https://github.com/mohiva/silhouette-akka-http/blob/master/project/BuildSettings.scala#L113). This can be tested locally by running `sbt test`.

**Comment by akkie** [comment]
[Here](https://github.com/mohiva/play-silhouette/blob/master/project/BuildSettings.scala#L115) is an example how it's done with Play.

**Comment by datalek** [comment]
Sorry I'll fix it! Thanks for advices. For next pull request I'll wait your review :)

**Comment by akkie** [comment]
Great, and thanks for your work :+1:

**Pull request merged**
