### PR TITLE
Fix some code formatting/style issues

### PR DESCRIPTION
**Pull request by akkie**
@datalek I've fixed some code formatting/style issues. In this context I've also fixed the doc issue.

### CODE REVIEW

**Comment by datalek** [comment]
@akkie Thx :)

**Comment by akkie** [comment]
@datalek Do you have seen the squash button as described in [this](https://github.com/blog/2141-squash-your-commits) post? If so, then it's better to use it to avoid merge commits. If not then maybe I must configure it for you.

**Comment by datalek** [comment]
@akkie ok, I've seen the button, for the next pr I'll use squash :+1:

**Comment by akkie** [comment]
:+1:

**Pull request merged**
